global:
  registry: "mo7iiee/robotshop"

services:
  web:
    repository: "mo7iiee/robotshop"
    tag: cart-20101726266
    port: 8080
    nodePort: 30080 

  catalogue:
    repository: "mo7iiee/robotshop"
    tag: cart-20101726266
    port: 8080

  cart:
    repository: "mo7iiee/robotshop"
    tag: cart-20101726266
    port: 8080

  user:
    repository: "mo7iiee/robotshop"
    tag: cart-20101726266
    port: 8080

  payment:
    repository: "mo7iiee/robotshop"
    tag: cart-20101726266
    port: 8080

  shipping:
    repository: "mo7iiee/robotshop"
    tag: cart-20101726266
    port: 8080

  ratings:
    repository: "mo7iiee/robotshop"
    tag: cart-20101726266
    port: 8080

  dispatch:
    repository: "mo7iiee/robotshop"
    tag: cart-20101726266
    port: 8080

  mongodb:
    repository: "mo7iiee/robotshop"
    tag: cart-20101726266
    port: 27017
    replicas: 1
    storage: 10Gi
    storageClass: gp2

  mysql:
    repository: "mo7iiee/robotshop"
    tag: cart-20101726266
    port: 3306
    replicas: 1
    storage: 10Gi
    storageClass: gp2
