global:
  registry: "mo7iiee/robotshop"

services:
  web:
    repository: "mo7iiee/robotshop"
    tag: web-20165352732
    port: 8080
    nodePort: 30080 

  catalogue:
    repository: "mo7iiee/robotshop"
    tag: catalogue-20165529676
    port: 8080

  cart:
    repository: "mo7iiee/robotshop"
    tag: "cart-20101726266"
    port: 8080

  user:
    repository: "mo7iiee/robotshop"
    tag: "user-20007175678"
    port: 8080

  payment:
    repository: "mo7iiee/robotshop"
    tag: payment-20165529679
    port: 8080

  shipping:
    repository: "mo7iiee/robotshop"
    tag: "shipping-20027024595"
    port: 8080

  ratings:
    repository: "mo7iiee/robotshop"
    tag: ratings-20165529685
    port: 8080

  dispatch:
    repository: "mo7iiee/robotshop"
    tag: "dispatch-20007175677"
    port: 8080

  mongodb:
    repository: "mo7iiee/robotshop"
    tag: "mongo"
    port: 27017
    replicas: 1
    storage: 10Gi
    storageClass: gp2

  mysql:
    repository: "mo7iiee/robotshop"
    tag: "mysql"
    port: 3306
    replicas: 1
    storage: 10Gi
    storageClass: gp2
