apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue
  labels:
    app: catalogue
spec:
  replicas: {{ .Values.services.catalogue.replicas | default 2 }}
  selector:
    matchLabels:
      app: catalogue
  template:
    metadata:
      labels:
        app: catalogue
    spec:
      containers:
        - name: catalogue
          image: {{ .Values.services.catalogue.repository }}:{{ .Values.services.catalogue.tag }}
          ports:
            - containerPort: {{ .Values.services.catalogue.port | default 8080 }}
