apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dispatch
  template:
    metadata:
      labels:
        app: dispatch
    spec:
      containers:
        - name: dispatch
          image: mo7iiee/robotshop:dispatch-20007175677
          ports:
            - containerPort: 8080
