apiVersion: apps/v1
kind: Deployment
metadata:
  name: dispatch
  labels:
    app: dispatch
spec:
  replicas: {{ .Values.services.dispatch.replicas | default 2 }}
  selector:
    matchLabels:
      app: dispatch
  template:
    metadata:
      labels:
        app: dispatch
    spec:
      containers:
        - name: dispatch
          image: {{ .Values.services.dispatch.repository }}:{{ .Values.services.dispatch.tag }}
          ports:
            - containerPort: {{ .Values.services.dispatch.port | default 8080 }}