name: Cart CI

on:
  push:
    branches:
      - main
    paths:
      - 'cart/**'
  pull_request:
    branches:
      - main
    paths:
      - 'cart/**'

jobs:
  build-and-deploy:
    name: Build, Push & Update Helm Chart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TOKEN }}

      - name: Docker Login
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/robotshop:cart-${{ github.run_id }} ./cart

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/robotshop:cart-${{ github.run_id }}

      - name: Update Helm chart tag
        run: |
          sed -i "s|tag: .*|tag: cart-${{ github.run_id }}|" helm/robotshop-chart/values.yaml

      - name: Commit and push Helm chart changes
        run: |
          git config --global user.email "mohie707034@gmail.com"
          git config --global user.name "mo7iee"
          git add helm/robotshop-chart/values.yaml
          git commit -m "Update Cart image tag to ${{ github.run_id }}"
          git push origin main