name: Cart CI

# Trigger the workflow on push or pull request to master,
# but only if files inside cart/ or the workflow file itself change
on:
  push:
    branches:
      - main
    paths:
      - 'cart/**'
  pull_request:
    branches:
      - main
    paths:
      - 'cart/**'

jobs:
  build-and-deploy:
    name: Build, Push & Deploy Cart
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Docker Login
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/robotshop:cart-${{ github.run_id }} ./cart

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/robotshop:cart-${{ github.run_id }}

      